add wrapper to track time
liamhickey/manufacturing-simulation pull request #4
Opened 2019-03-30 03:28 UTC by liamhickey

2019-03-30 03:32 UTC, acournoyer1 approved these changes

2019-03-30 03:32 UTC, acournoyer1 commented on src/Component.java
> +	c3;
Lol why did this change?

2019-03-30 03:32 UTC, acournoyer1 requested changes
If you're gonna make a wrapper can you give the components an id too while you're at it?

2019-03-30 03:36 UTC, liamhickey commented on src/Component.java
> +	c3;
oh, lol, i was looking at adding the fields there, and if you add additional stuff underneath those in the enum you have to add a colon

2019-04-01 16:18 UTC, liamhickey commented
conflicts existed with the other PR

2019-04-02 00:51 UTC, merged